AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 
  Construct bookshare.codeequity.net s3 bucket

Resources:

  BookShareBucket:
    Type: AWS::S3::Bucket
    Properties:
      # AWS CloudFormation resource to create an S3 bucket
      BucketName: bookshare.codeequity.net
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    #DeletionPolicy: Retain
    
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: CEBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BookShareBucket
                - /*
      Bucket: !Ref BookShareBucket
  

Outputs:
  BucketID:
    Value: !GetAtt BookShareBucket.Arn
    Description: URL for website hosted on S3
    Export:
      Name: !Sub "${AWS::StackName}-CES3ID"
  WebsiteURL:
    Value: !GetAtt BookShareBucket.WebsiteURL
    Description: URL for website hosted on S3
    Export:
      Name: !Sub "${AWS::StackName}-CES3URL"
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - BookShareBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
