name: CI

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    
    - name: Where are we
      run: ls -la
    
    - name: Where is working dir
      working-directory: ${{ github.workspace }}
      run: ls -la
    
    - name: Get flutter
      working-directory: ./bookshareApp/book_flutter
      run: flutter pub get
    
    - name: Run tests
      working-directory: ./bookshareApp/book_flutter
      run: flutter test
