name: CI

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
   
    - name: check location
      working-directory: ./bookShareApp/book_flutter
      run: ls -la
    
    - name: Get flutter
      working-directory: ./bookShareApp/book_flutter
      run: flutter pub get
    
    - name: Run tests
      working-directory: ./bookShareApp/book_flutter
      run: flutter test 
