on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: subosito/flutter-action
      with:
        flutter-version: '^1.13.6'
    - run: flutter pub get
    - run: flutter test
